In [4]:
import numpy as np
l=range (1000000)
d=np.arange (1000000)
print (d)


[     0      1      2 ... 999997 999998 999999]


In [5]:
%time for i in range (1,10): r=[x*2 for x in l]
    

Wall time: 1.28 s


In [6]:
%time for i in range (1,10): r=d*2
    

Wall time: 55 ms


In [10]:
x = np.arange(9).reshape((3,3))
x
    

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
x.sum(axis=1)

array([ 3, 12, 21])

In [12]:
x = np.array([0, 1, 2], float)
x

array([0., 1., 2.])

In [13]:
x = np.array([1, 2])
y = np.array([[3], [4]])
x+y

array([[4, 5],
       [5, 6]])

In [14]:
x = np.mat([[1, 2], [3, 4]])
x

matrix([[1, 2],
        [3, 4]])

In [15]:
x**2

matrix([[ 7, 10],
        [15, 22]])

In [17]:
 x = np.array([1, 2, 3])
 x.repeat(2)


array([1, 1, 2, 2, 3, 3])

In [21]:
x = range(5)
x[::-1]


range(4, -1, -1)

In [22]:
x=np.array([[1, 2], [3, 4]])
x[:, 1]

array([2, 4])

In [24]:
dt = np.dtype([('a', np.int32), ('b', np.float32, (3,))])
np.zeros(3, dtype=dt)

array([(0, [0., 0., 0.]), (0, [0., 0., 0.]), (0, [0., 0., 0.])],
      dtype=[('a', '<i4'), ('b', '<f4', (3,))])

In [28]:
a= np.array([[1, 2, 3], [4, 5, 6]])
print(a[0,2] + a[1,1])



8


In [30]:
r = np.array([1, 2, 3, 4, 5, 6, 7])

print(r[-3:-1])

[5 6]


In [31]:
a = np.array([1, 0, 3])

newa = a.astype(bool)

print(newa)
print(newa.dtype)

[ True False  True]
bool


In [32]:
a = np.array([1, 2, 3, 4, 5])
x = a.view()
x[0] = 31

print(a)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [33]:
a = np.array([1, 2, 3, 4], ndmin=5)
print(a)
print('shape of array :', a.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [34]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newa = a.reshape(4, 3)

print(newa)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
a = np.array([1, 2, 3])

for x in a:
  print(x)

1
2
3


In [36]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in a:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [37]:
for x in a:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [38]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(a):
  print(x)

1
2
3
4
5
6
7
8


In [39]:
a1 = np.array([1, 2, 3])

a2 = np.array([4, 5, 6])

a = np.concatenate((a1, a2))

print(a)

[1 2 3 4 5 6]


In [40]:
a = np.hstack((a1, a2))

print(a)

[1 2 3 4 5 6]


In [44]:
a = np.vstack((a1, a2))
print (a)

[[1 2 3]
 [4 5 6]]


In [45]:
a = np.dstack((a1, a2))

print(a)

[[[1 4]
  [2 5]
  [3 6]]]


In [46]:
a = np.array([1, 2, 3, 4, 5, 6])

newa = np.array_split(a, 4)

print(newa)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [47]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newa = np.array_split(a, 3, axis=1)

print(newa)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [48]:
a = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(a == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [49]:
a = np.array([6, 7, 8, 9])

x = np.searchsorted(a, 7)

print(x)

1


In [50]:
a = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(a))

[[2 3 4]
 [0 1 5]]
